repo: https://github.com/pooneyy/Container-Images-Publisher

ref: main

image_name: php

# renovate: datasource=docker depName=php
image_tag_prefix: 8.1.34-fpm-bookworm

image_tag: -php-unofficial,8.1-fpm-bookworm-php-unofficial

build_context: .

dockerfile: .github/configs/php/8.1/Dockerfile

architectures: linux/amd64, linux/arm64, linux/arm/v7, linux/arm/v5, linux/386, linux/mips64le, linux/ppc64le, linux/s390x

build_args: 

build_target: 
