repo: https://github.com/Stremio/stremio-web

# renovate: datasource=github-releases depName=Stremio/stremio-web
ref: v5.0.0-beta.29

image_name: stremio-web

# renovate: datasource=github-releases depName=Stremio/stremio-web
image_tag: 5.0.0-beta.29,latest

build_context: .

dockerfile: Dockerfile

architectures: linux/amd64, linux/arm64, linux/arm/v7

build_args: 

build_target: 