repo: https://github.com/pooneyy/Container-Images-Publisher

ref: main

image_name: php

# renovate: datasource=docker depName=php
image_tag_prefix: 8.4.17-fpm-bookworm

image_tag: -php-unofficial,8.4-fpm-bookworm-php-unofficial

build_context: .

dockerfile: .github/configs/php/8.4/Dockerfile

architectures: linux/amd64, linux/arm64, linux/arm/v7

build_args: 

build_target: 
