runs_on: self-hosted

build_parallelism: 2

repo: https://github.com/pooneyy/Container-Images-Publisher

ref: main

image_name: squid

# renovate: datasource=github-tags depName=squid-cache/squid
image_tag: 7.4,7,latest

build_context: .github/configs/squid

dockerfile: .github/configs/squid/Dockerfile

architectures: linux/amd64, linux/arm64, linux/arm/v7, linux/ppc64le, linux/riscv64, linux/s390x

# renovate: datasource=github-tags depName=squid-cache/squid
build_args: SQUID_VERSION=7.4

build_target: 